version: '3.7'

services:
  web:
    image: nginx:latest
    container_name: my-first-calculator
    ports:
      - '80:80'
    volumes:
      - ./src:/src
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-first-calculator-network
    depends_on:
      - php
  php:
    container_name: my-first-calculator-php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
        - ./src:/src
    ports:
      - '1337:1337'
    networks:
      - my-first-calculator-network
    depends_on:
      - db
  db:
    container_name: my-first-calculator-db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: myfirstcalculator
      MYSQL_ROOT_PASSWORD: c41cu14t0rs4r34n00bs
    ports:
      - '3306:3306'
    networks:
      - my-first-calculator-network
  
networks:
  my-first-calculator-network:
    driver: bridge
  